### PR TITLE
Introduce plugin management system

### LINKED ISSUE #3: Plugin management system
- [x] based on git
- [ ] every function call is recorded into a script that acts as a 'reproducible log'
- [ ] wrap the script in its own function
- [ ] automatically push to remote repo
- [x] automatically manage versions: git tags if available, or git hash otherwise
- [x] add plugins by adding URL of git repo
- [x] the core of Napari is just the minimal plugin system, everything is plugin based, even the plugin core, this way we have a unified way to push updates to users. Users can also add their own user defined plugins, and first class contributions can be added to the official distribution. 
- [x] Each repo has a 'configuration' file that describes the plugins present in the repo, what kind of plugins these are (viewer, processing, analysis, ... ), how and where they get integrated into the GUI menus, and where to find the 'entry point' python file within the repo.
- [x] We need some sort of 'interface' scheme to normalise how the host python code will interact with the plugin code... What is the pythonic way to do it?

### PR DESCRIPTION
**Pull request by kne42**
# Description
Introduces a plugin management system (and necessary utility functions for general configuration files).

The specification for this system is as follows:
- Configuration files are stored in the directory: `~/.napari`. This follows suit with the other alternate directories found in the [jupyter configuration convention](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html), including the environment variable `NAPARI_CONFIG_DIR`.
- Among other user-editable configuration files is the `plugins.yaml` file. This contains information about what plugins are installed.

<details>
<summary>plugins.yml specification</summary>

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "fileMatch": [
    "plugins.yml"
  ],
  "definitions": {
    "git_url": {
      "description": "Repository git source URL.",
      "type": "string",
      "TODO": "add actual http(s)://{...}.git pattern"
    }
  },
  "properties": {
    "plugins": {
      "description": "List of plugin sources.",
      "type": "array",
      "items": {
        "type": "object",
        "anyOf": [
          { 
            "properties": {
              "git_source": { "$ref": "#/definitions/git_url" },
              "version": {
                "description": "The git branch/tag/commit to use as a source.",
                "type": "string"
              },
              "development": {
                "description": "If enabled, will treat the repository as a normal folder (no version control)."
              }
            },
            "required": ["git_source"]
          },
          {
            "properties": { 
              "folder": {
                "description": "The folder from which the plugin is sourced. Can be used with 'git_source' to handle repository name collisions.",
                "type": "string"
              }
            },
            "required": ["folder"]
          }
        ]
      }
    }
  },
  "required": ["plugins"]
}
```
</details>

<details>
<summary>example plugins.yml file</summary>

```yaml
plugins:
  - git_source: github.com/jni/foo.git

  - git_source: github.com/kne42/foo.git
    folder: bar

  - folder: baz

  - git_source: github.com/Napari/hello-world-plugin.git
    version: 1.0
    development: yes
```
</details>
<br>

- Plugins will be cloned into the `plugins` configuration directory and a remote named `source` with the git url will be created.
- To set a plugin to a specific version, the manager will check out the version to the `source` branch with `git checkout git-reference -B source`.
- If no version is provided, the manager will check out the latest stable version or the default branch if it is not found.
- `version: development` will cause the manager to ignore updating the repository with git.
- When updating, the manager will check each folder for a `napari.yml` file, which contains important information about the plugin.

<details>
<summary>napari.yml specification</summary>

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "fileMatch": [
    "napari.yml"
  ],
  "definitions": {
    "git_url": {
      "description": "Repository git source URL.",
      "type": "string",
      "TODO": "add actual http(s)://{...}.git pattern"
    },
    "filepath": {
      "type": "string",
      "TODO": "add regex pattern"
    },
    "python_file": {
      "type": "string",
      "TODO": "add regex pattern"
    },
    "python_module_name": {
      "type": "string",
      "TODO": "add regex pattern"
    },
    "version": {
      "oneOf": [
        {
          "description": "The exact version.",
          "type": "string"
        },
        {
          "description": "The minimum/maximum version.",
          "type": "object",
          "properties": {
            "minimum": { "type": "string" },
            "maximum": { "type": "string" },
            "min": { "type": "string" },
            "max": { "type": "string" }
          },
          "anyOf": [
            { "oneOf": [
              { "required": ["minimum"] },
              { "required": ["min"] }
            ]},
            { "oneOf": [
              { "required": ["maximum"] },
              { "required": ["max"] }
            ]},
          ]
        }
      ]
    }
  },
  "properties": {
    "plugin_info": {
      "description": "Information about the plugin.",
      "properties": {
        "author_name": {
          "description": "The plugin maintainer's name.",
          "type": "string"
        },
        "author_email": {
          "description": "The plugin maintainer's email.",
          "type": "string",
          "format": "email"
        },
        "short_description": {
          "description": "A short description of the plugin.",
          "type": "string"
        },
        "plugin_name": {
          "description": "The name that the plugin will be available under in napari.plugins.",
          "$ref": "#/definitions/python_module_name"
        },
        "path": {
          "description": "Path to the python source file.",
          "oneOf": [
            { "$ref": "#/definitions/python_file" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/python_file" }
            }
          ]
        },
        "paths": {
          "description": "Paths to the python source files.",
          "type": "array",
          "items": { "$ref": "#/definitions/python_file" }
        }
      },
      "allOf": [
        { "required": ["plugin_name"] },
        { "oneOf": [
          { "required": ["path"] },
          { "required": ["paths"] }
        ]}
      ]
    },
    "redirect": {
      "description": "If this repository is no longer being maintained, please redirect to another one.",
      "$ref": "#/definitions/git_url"
    },
    "plugin_dependencies": {
      "description": "A list of depended-on plugins.",
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/git_url" },
          {
            "type": "object",
            "properties": {
              "git_source": { "$ref": "#/definitions/git_url" },
              "version": { "$ref": "#/definitions/version" },
              "namespace": { "$ref": "#/definitions/python_module_name" }
            },
            "required": ["git_source"]
          }
        ]
      }
    },
    "pip_requirements": {
      "description": "A requirements.txt file or a list of pip requirements to install.",
      "oneOf": [
        {
          "description": "Location of the requirements.txt file.",
          "$ref": "#/definitions/filepath"
        },
        {
          "description": "pip requirement.",
          "type": "string"
        }
      ]
    },
    "napari_version": {
      "description": "The exact napari version to specify or the bounds for it.",
      "$ref": "#/definitions/version"
    },
    "update_script": {
      "description": "The python script to run upon updating the repository.",
      "$ref": "#/definitions/python_file"
    }
  },
  "required": ["plugin_info"]
}
```
</details>
<br>

- To load plugins, `napari.plugins.__init__.py` will comb through the `plugins` configuration directory and import the corresponding modules (found because they were named `plugin_info.plugin_name`) as `napari.plugins` + `plugin_info.plugin_name` by adding them to `sys.modules`.

# References
Closes #3

### CODE REVIEW

**Comment by royerloic** [comment]
Really cool Kira. Should I merge already?

**Comment by kne42** [comment]
@royerloic Haha, not even close! I like to open up PRs for WIP features so that others can track my progress (and to call dibs on an issue) :P

Besides, I think that we should usually have you and/or @jni review the changes before a merge.

I’ll let you know when it’s ready for its first review!

**Comment by royerloic** [comment]
Haha, ok cool, sensed that it was just the beginning, but looks already great! I like your attention to details!

**Comment by kne42** [comment]
@royerloic @jni I added a proposed plugins specification in the PR description if you want to check that out :)

**Comment by royerloic** [comment]
Hi Kira,

Very nice, I like that you are considering all sorts of plugin types,
from pip-based to git-based…

**Comment by kne42** [comment]
An example of the remote plugin updating can be found in [this gist](https://gist.github.com/kne42/0a524126df130978d2f1b4fe82dec890).

**Comment by kevinyamauchi** [comment]
Hey, Kira. This looks awesome! We haven't met yet, but I am an engineer at the Biohub. I was chatting with Loic and I would like to contribute a couple of image loading plugins related to the imaging database at the Biohub and our in situ transcriptomics work. 

Would it be possible to chat about the plugin API for IO plugins sometime next week?

Also, a couple of comments on the plugin install:
- Do you think it is necessary to support so many different plugin description/manifest designs (.yaml, __init__, main.py)? I think if we have a single standard, it's easier to check for compliance and also it's easier to understand new plugins quickly. I suppose the counterpoint is that by being flexible, it may be possible to use some existing plugins/modules without modification.
- Perhaps a bit early to discuss this, but what do you think about creating base classes that provide the required elements of plugins (perhaps one for each type? io, image transform, etc.) and then plugin contributors create subclasses of the appropriate base class?

**Comment by kne42** [comment]
@kevinyamauchi 
> Hey, Kira. This looks awesome! We haven't met yet, but I am an engineer at the Biohub. 

Hi Kevin! I'm glad that you're super excited about this project as well 😄 

> I was chatting with Loic and I would like to contribute a couple of image loading plugins related to the imaging database at the Biohub and our in situ transcriptomics work. 

Great! That would be awesome! It would be especially nice if we could get these plugins to load in the proper metadata as well (see #5).

> Would it be possible to chat about the plugin API for IO plugins sometime next week?

Definitely! You can find me at Cubicle #164 in the Accelerator on Mondays, Wednesdays, and Fridays.

> Also, a couple of comments on the plugin install:
> - Do you think it is necessary to support so many different plugin description/manifest designs (.yaml, __init__, main.py)? I think if we have a single standard, it's easier to check for compliance and also it's easier to understand new plugins quickly. I suppose the counterpoint is that by being flexible, it may be possible to use some existing plugins/modules without modification.

Actually Loic and I finally had an opportunity to discuss this in person yesterday – I am redesigning the system as we speak! I agree that the current design is far too messy and am working to standardize it by requiring all of the main plugin information to be held within the repository's specification file and simplifying the main index file to comprising of (mostly) a bunch of urls. I'll update the specification in the description and let y'all know of the changes via comment when I'm done!

> - Perhaps a bit early to discuss this, but what do you think about creating base classes that provide the required elements of plugins (perhaps one for each type? io, image transform, etc.) and then plugin contributors create subclasses of the appropriate base class?

Sorry, I don't quite follow. Perhaps you could flush out your idea more in #15?

**Comment by kne42** [comment]
Ok, the new specifications have been (roughly) outlined in the PR description.

**Comment by jni** [comment]
Hi @kevinyamauchi!

I'm excited to see Napari growing so fast already! Clearly a lot of people have been silently wishing for something like this.

> Perhaps a bit early to discuss this, but what do you think about creating base classes that provide the required elements of plugins (perhaps one for each type? io, image transform, etc.) and then plugin contributors create subclasses of the appropriate base class?

Over at scikit-image, and to a similar extent at SciPy and NumPy, we favour a functional programming style. I would strongly prefer that plugins were simple type-annotated functions. We can then use the types to automatically generate a GUI dialog.

**Comment by kevinyamauchi** [comment]
Thanks for the quick responses! @kne42, I'll send you an email about meeting to discuss the plugin API (focusing on image IO). 

@jni, that works for me! This project would be super useful for our work and I'd be stoked to contribute!

**Comment by kne42** [comment]
@pep8speaks resume

**Comment by kne42** [comment]
@orkohunter the bot does not appear to be updating; any ideas? Might be because I've force pushed idk

**Comment by OrkoHunter** [comment]
Hello @kne42!

Thank you for bringing this to my notice. I got to debug on the issue. GitHub and Heroku keep telling me "Service Timeout" after several retries as well.

I used the same payload corresponding to this PR on a local version of the server and it passed (hence the updated comment). However, GitHub again gave me a Service timeout for the latest commit you just pushed.

I can not seem to figure out why this issue is happening with this PR, while the service is running perfectly fine for all the other events for other repos/PRs.

Excuse me for this behavior. I do not have a helpful response for it now.

screen shot 2018-09-04 at 10 53 36 pm

**Comment by ctrueden** [comment]
I ask this naively, since I am not a very proficient Python programmer—and apologies if I misunderstand what this PR is trying to accomplish—but would it makes sense to consider building on some general-purpose Python plugin framework like [PluginBase](https://github.com/mitsuhiko/pluginbase)?

**Comment by royerloic** [comment]
> I ask this naively, since I am not a very proficient Python programmer—and apologies if I misunderstand what this PR is trying to accomplish—but would it makes sense to consider building on some general-purpose Python plugin framework like [PluginBase](https://github.com/mitsuhiko/pluginbase)?

Hi Curtis!
Nice to see you here.
So, the idea is to have a plugin system that is entirely git based.
:-)

**Comment by kne42** [comment]
Hi @ctrueden,

Thank you for your input! We have, at this time, not found any suitable existing Python plugin systems to use as a base. The repository that you linked appears to be a convoluted workaround of specifying a `__path__` attribute to a module's `__init__.py`. Additionally, it works by replacing the built-in  `__import__`, which is not only bad practice, but could be implemented much more cleanly with a [custom import hook](https://docs.python.org/3/reference/import.html#finders-and-loaders). Regardless, this implementation is not suitable as our import system needs to find and load individual files instead of specifying additional package search locations on the fly.

To answer your other question, the scope of this PR goes far beyond just loading plugins. It uses git to actually install and download plugins (hoping to eventually model it after [`straight.el`](https://github.com/raxod502/straight.el)) and loads them according to their entry point specifications. It additionally provides a central hub for registering plugins' functions to be populated in the GUI.

**Comment by ctrueden** [comment]
Thanks for the detailed reply, @kne42. Related question: would this feature be useful as a reusable module, beyond only Napari?

I am also curious about the 5-10 year vision of this project in general, but probably this issue is not the ideal place to discuss that. I [commented in #9 accordingly](https://github.com/Napari/napari/issues/9#issuecomment-424426277).

**Comment by kne42** [comment]
While this isn't perfected, I think it's a good enough start to merge since it is only an "introduction" after all.

**Comment by royerloic** [comment]
Perfect Kira!
step by step 😀

- Loic

**Pull request merged**
